### ISSUE TITLE
CodePen: 'rebem-css' is not a valid postcss plugin

### ISSUE THREAD

**Issue by ilyar** [rebem/css#5]
## Setup
CSS Preprocessor: PostCSS http://codepen.io/ilyar/pen/dvJVaa
## Actual result
http://codepen.io/ilyar/pen/dvJVaa.css
```css
@use rebem-css;

:block(block)
{
   color: #0f0;
}
// 'rebem-css' is not a valid postcss plugin.
```
## Expected Result
```css
.block
{
   color: #0f0;
}
```
